// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
    static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJtaV8fTq74WBRKGncvHza3ABPMDdKKk8',
    appId: '1:1072698470757:android:845fd54474db33cb0ff18c',
    messagingSenderId: '1072698470757',
    projectId: 'huzaipha-flutter',
    storageBucket: 'huzaipha-flutter.appspot.com',
  );
    static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uuoHO_sxhaY1OUjV8PVs0mnuh1o3-hE',
    appId: '1:1072698470757:web:054593c8b00eddb00ff18c',
    messagingSenderId: '1072698470757',
    projectId: 'huzaipha-flutter',
    authDomain: 'huzaipha-flutter.firebaseapp.com',
    storageBucket: 'huzaipha-flutter.appspot.com',
    measurementId: 'G-W1LQM25H5B',
  );


}


